### ISSUE TITLE
Липсващи знамена

### ISSUE THREAD

**Issue by Hristov-Metodi** [vexelon-dot-net/currencybg.app#10]
На някои валути няма знамена, а излизат сиви правоъгълничета с питанка по средата.
![screenshot_20160506-220721](https://cloud.githubusercontent.com/assets/1789731/15083763/c4153118-13d7-11e6-9e52-47206dd66149.png)
![screenshot_20160506-220657](https://cloud.githubusercontent.com/assets/1789731/15083769/c93da936-13d7-11e6-85f0-a66a2ae0c0f7.png)

**Comment by petarov** [comment]
Знамената са от [безплатен пакет](https://icons8.com), който е непълен. Липсващите просто имат default икона. Ще трябва да намерим алтернативен пакет.

**Comment by Hristov-Metodi** [comment]
ATS - Australian Shilling (NOT USED ANYMORE: After decimalisation on 14 February 1966, it was equal to 10¢)
BEF - Belgian Franc (EUR since 2002)
CYP - Cyprus Pound (EUR since 2008)
DEM - Deutsche Mark (EUR since 2002)
NLG - Dutch Gulden (EUR since 2002)
FIM - Finnish Markka (EUR since 2002)
FRF - French Franc (EUR since 2002)
GRD - Greek Drachma (EUR since 2002)
IEP - Irish Pound (EUR since 2002)
ITL - Italian Lira (EUR since 2002)
LUF - Luxemburg Frank (EUR since 2002)
MTL - Maltese Lira (EUR since 2008)
**ILS - New Israel Shekel (FOUND)**
PTE - Portuguese Escudo (EUR since 2002)
SKK - Slovakian Koruna (EUR since 2008)
SIT - Slovenian Tolar (EUR since 2007)
ESP - Spanish Peseta (EUR since 2002)

**Comment by Hristov-Metodi** [comment]
ils.png (ILS - New Israel Shekel) добавен в: currencybg.app/res/drawable/

**Comment by petarov** [comment]
@Hristov-Metodi  алфа версията може да се сваля, така че като имаш време хвърли 1 око на знамената

**Comment by Hristov-Metodi** [comment]
@petarov Млако се поомотах. Git не ми е от силните страни :) Как и от къде се сваля.

**Comment by petarov** [comment]
Ето [линка](https://play.google.com/apps/testing/net.vexelon.currencybg.app) :)
