### ISSUE TITLE
Не работещ ENTER бутон

### ISSUE THREAD

**Issue by Hristov-Metodi** [vexelon-dot-net/currencybg.app#11]
При конвертиране, ако се смени сумата която трябва да се изчисли, трябва да се натисне BACK бутона (на телефона) за да се види преизчислената сума. В старата версия това става с ENTER, но тук това не работи.
![20160506_222020](https://cloud.githubusercontent.com/assets/1789731/15083962/17a4e822-13d9-11e6-9b9c-18cc7da00480.png)

**Comment by petarov** [comment]
Трябва да е ок в новата алфа версия.
