### ISSUE TITLE
Празно пространство

### ISSUE THREAD

**Issue by Hristov-Metodi** [vexelon-dot-net/currencybg.app#12]
Избраната валута за конвертиране се мести надоло и частично се крие зад клавиатурата, вместо да седи най-отгоре на екрана (под **Convert)**.
![20160506_222052](https://cloud.githubusercontent.com/assets/1789731/15083935/e90d2920-13d8-11e6-9f5d-53b500cdf5de.png)

**Comment by petarov** [comment]
Мда, това не съм го забелязал. Добър _улов_. ;)

**Comment by petarov** [comment]
Трябва да е ок в новата алфа версия.
