### ISSUE TITLE
Не работи свалянето на валути

### ISSUE THREAD

**Issue by petarov** [vexelon-dot-net/currencybg.app#13]
Явно има проблем при сайта на БНБ. Не се свлят никакви валути и сервиса crash-ва допълнително приложението. Трябва да се проучи причината. Евентуално ще е нужен hot fix.

**Comment by Tsvetoslav88** [comment]
До колкото видях проблема е в динамичните валути(метод - getFixedRates). Ще пробвам да видя какво се случва, но някой неща не са ми все още настроени на новия компютър и имам малко затруднение с дебъгването на кода.

**Comment by Tsvetoslav88** [comment]
БНБ са сменили HTML-а за фиксираните валути. Направих тази корекция локално "Element div = doc.select("div#content_box.content > div.doc_entry > center > table > tbody").first();" и изглежда да работи. Този ред се намира в метод getFixedRates, който пък се намира в клас BNBSource. Ако искаш пробвай го и ти, и ако всичко е наред го качи в google play.
![bnb](https://cloud.githubusercontent.com/assets/8929789/17465276/9754264e-5cfb-11e6-9195-46db9a2b1700.jpg)

**Comment by Tsvetoslav88** [comment]
За да няма грешки, ти прикачам разликите в класа:
![gitdiff](https://cloud.githubusercontent.com/assets/8929789/17465311/8b31828e-5cfc-11e6-9881-5eab39b3f827.jpg)

**Comment by petarov** [comment]
Супер! 👍  Направо дай един бранч и pull request и ще го чекна така най-добре.

**Comment by Tsvetoslav88** [comment]
Готово. Направих нов бранч "bug/#13_BNB_FixedRates_Problem]" на база на "master", като в него нанесох промените в кода. Направих му pull request.

**Comment by petarov** [comment]
Оправено в 1.0.1
