### ISSUE TITLE
Рефакторинг на API слой

### ISSUE THREAD

**Issue by Tsvetoslav88** [vexelon-dot-net/currencybg.app#15]
Приложението изчита данните за валути от новия сървър

**Comment by Tsvetoslav88** [comment]
Логиката, която трябва да бъде използвана в приложението е - проверява в базата към коя дата и час последно има записани валути. Датата на последно получените валути се подава към сървъра, за да може той да върне данните, който са се изчели от източниците след тази дата и час. Приложението записва върната информация. На потребителя му се визуализират валутите до (X) време назад от текущата дата и час. Ако приложението прави за първи път изчитане на валутите се подава предефинирано време (Y) назад от текущата дата и час към сървъра. В приложението се съхраняват данните до (N) дни назад, след което се изтриват - може да се ползва сървиса като Scheduled job

**Comment by petarov** [comment]
Само за info. Това issue зависи от точка 2-ра на issue #3. След fix на точката, затваряме и това.

**Comment by petarov** [comment]
Вътре с PR #29
