### ISSUE TITLE
Back-end calculator

### ISSUE THREAD

**Issue by Tsvetoslav88** [vexelon-dot-net/currencybg.app#24]
Създаваме на Back-end калкулатор, който съдържа следните 4 метода:
BigDecimal add(BigDecimal x, BigDecimal y);
BigDecimal substract(BigDecimal x, BigDecimal y);
BigDecimal divide(BigDecimal x, BigDecimal y);
BigDecimal multiply(BigDecimal x, BigDecimal y);
, които ще се викат от потребителски интерфейс.

**Comment by petarov** [comment]
Почнал съм да ръчкам calculator UI-a.

**Comment by petarov** [comment]
PR #31
