### ISSUE TITLE
Моят портфейл

### ISSUE THREAD

**Issue by Hristov-Metodi** [vexelon-dot-net/currencybg.app#5]
Данни за наличните валутни запаси на потребителя:
- Вид закупена валута
- Сума
- Датата на закупуване
- Курса на закупуване

При отваряне на портфейла той автоматично изтегля последните актуални данни за курс продава, смята колко е печалбата или загубата от инвестицията

**ОПЦИЯ 1:** Дава съвет как да постъпи потребителя – чака, купува още или продава

**Comment by petarov** [comment]
@Hristov-Metodi Алгоритъм за изчисляване на валутите в портфейла.

**Comment by petarov** [comment]
TODOs База от данни:

  1.  Нова таблица `Wallet` + Upgrade в `CurrenciesSQLiteDB.java`. Версия 4 на дб-то.
  2.  CRUD на `WalletEntry` (`addWalletEntry`, `deleteWalletEntry`,  `updateWalletEntry`, `getWalletEntries`)

**Comment by Tsvetoslav88** [comment]
Здравей Пепи. Беше казал за DB имплементацията да работя в бранча за Wallet, а гледам, че такъв няма. Да направя ли?

**Comment by Tsvetoslav88** [comment]
Нещата по базата са готови и качени в бранча. Ако нещо не работи или липсва ми пиши :)
