### ISSUE TITLE
Бутон за обновяване на "Портфейл"

### ISSUE THREAD

**Issue by Tsvetoslav88** [vexelon-dot-net/currencybg.app#78]
Да се помисли дали поведението на "Портфейл" да не е подобно на "Преобразуване". При избиране на "Портфейл" се прави автоматично обновяване на състоянието му. Да се помисли има нужда от тоя бутон за обновяване?
![default](https://user-images.githubusercontent.com/8929789/30289931-6df54dc0-9736-11e7-8b24-6a522118fb95.png)

**Comment by petarov** [comment]
Impl. в `3.2.1`
